package com.linkedin.openhouse.optimizer.entity;

import com.linkedin.openhouse.optimizer.api.model.OperationMetrics;
import com.linkedin.openhouse.optimizer.api.model.OperationStatus;
import com.linkedin.openhouse.optimizer.api.model.OperationType;
import com.linkedin.openhouse.optimizer.config.OperationMetricsConverter;
import java.time.Instant;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * JPA entity representing an Analyzer recommendation for a table maintenance operation.
 *
 * <p>One row per {@code (database_name, table_name, operation_type)}, enforced by the unique
 * constraint {@code idx_unique_op}. The Analyzer upserts this row; the Scheduler claims it by
 * updating {@code status} to {@code SCHEDULED} and setting {@code scheduled_at}. Metrics are
 * denormalized from {@code table_stats} at analysis time to create an immutable audit snapshot of
 * what drove the scheduling decision.
 */
@Entity
@Table(
    name = "table_operations",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "idx_unique_op",
          columnNames = {"database_name", "table_name", "operation_type"})
    },
    indexes = {
      @Index(name = "idx_db_name", columnList = "database_name"),
      @Index(name = "idx_table_name", columnList = "table_name"),
      @Index(name = "idx_op_type", columnList = "operation_type"),
      @Index(name = "idx_status", columnList = "status"),
      @Index(name = "idx_created_at", columnList = "created_at"),
      @Index(name = "idx_scheduled_at", columnList = "scheduled_at")
    })
@Getter
@EqualsAndHashCode
@Builder(toBuilder = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PROTECTED)
public class TableOperationsRow {

  /** UUID generated by the Analyzer at creation time. */
  @Id
  @Column(name = "id", nullable = false, length = 36)
  private String id;

  @Column(name = "database_name", nullable = false, length = 255)
  private String databaseName;

  @Column(name = "table_name", nullable = false, length = 255)
  private String tableName;

  @Enumerated(EnumType.STRING)
  @Column(name = "operation_type", nullable = false, length = 50)
  private OperationType operationType;

  /** {@code PENDING} until the Scheduler claims the row; then {@code SCHEDULED}. */
  @Enumerated(EnumType.STRING)
  @Column(name = "status", nullable = false, length = 20)
  private OperationStatus status;

  /** When the Analyzer first created this row. Set by the service on insert; never updated. */
  @Column(name = "created_at", nullable = false)
  private Instant createdAt;

  /** Set by the Scheduler when claiming; {@code null} while {@code PENDING}. */
  @Column(name = "scheduled_at")
  private Instant scheduledAt;

  @Version
  @Column(name = "version")
  private Long version;

  /**
   * Denormalized stats snapshot captured at analysis time: table size, snapshot count, and file
   * counts as of the moment the Analyzer ran.
   */
  @Convert(converter = OperationMetricsConverter.class)
  @Column(name = "metrics")
  private OperationMetrics metrics;
}
