package harness

/** Mixes the complete standard, RTAS, merge-on-read, branch, and WAP catalog. */
object Scenarios
    extends DmlScenarios
    with NestedTypesScenarios
    with MaintControlScenarios
    with ForkScenarios
    with NegativeDdlScenarios
    with InteractionScenarios
    with SurfaceScenarios
    with HazardReaderWriterScenarios
    with ImplementationPinScenarios
    with RtasDmlScenarios
    with RtasDdlScenarios
    with RtasInteractionScenarios
    with RtasSurfaceScenarios
    with RtasHazardScenarios
    with MorDmlScenarios
    with MorMaintScenarios
    with MorReaderWriterScenarios
    with MorInteractionScenarios
    with MorSurfaceScenarios
    with MorForkScenarios
    with BranchDmlScenarios
    with BranchWapScenarios
    with BranchInteractionScenarios
    with BranchSurfaceScenarios
    with BranchHazardScenarios
    with BranchMorScenarios
