-- Optimizer Service Schema (MySQL)
-- 2 tables: table_operations, table_operations_history
-- Note: table_stats lives in the housetables service.
CREATE TABLE
  IF NOT EXISTS table_operations (
    id VARCHAR(36) NOT NULL COMMENT 'UUID generated by Analyzer',
    database_name VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL COMMENT 'PENDING or SCHEDULED',
    created_at TIMESTAMP(6) NOT NULL COMMENT 'When the Analyzer first created this row',
    scheduled_at TIMESTAMP(6) COMMENT 'Set by Scheduler when claiming; null when PENDING',
    version BIGINT COMMENT '@Version optimistic lock counter',
    metrics JSON COMMENT 'Denormalized stats: table_size_bytes, num_snapshots, num_files_added, num_files_deleted',
    PRIMARY KEY (id),
    UNIQUE INDEX idx_unique_op (database_name, table_name, operation_type),
    INDEX idx_db_name (database_name),
    INDEX idx_table_name (table_name),
    INDEX idx_op_type (operation_type),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_scheduled_at (scheduled_at)
  ) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE
  IF NOT EXISTS table_operations_history (
    id BIGINT NOT NULL AUTO_INCREMENT,
    database_name VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    submitted_at TIMESTAMP(6) NOT NULL COMMENT 'When the Spark job was submitted / ran',
    status VARCHAR(20) NOT NULL COMMENT 'SUCCESS or FAILED',
    job_id VARCHAR(255) COMMENT 'Spark job ID',
    result JSON COMMENT 'error_message, error_type; evolves without schema changes',
    PRIMARY KEY (id),
    INDEX idx_db_table_hist (database_name, table_name),
    INDEX idx_op_type_hist (operation_type),
    INDEX idx_submitted_at (submitted_at),
    INDEX idx_status_hist (status),
    INDEX idx_job_id (job_id)
  ) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
